services:
  - type: web
    name: practica05-django-mvt
    runtime: python
    plan: free
    rootDir: PRACTICA05_DjangoModelViewTemplate
      buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && python manage.py crear_datos_demo
    startCommand: gunicorn practica05_DjangoMVT.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
